trycatch: do not try catch when no exceptions is enabled
For WASM targets the `cc` crate changed to always set `-fno-exceptions`,
before only `-fignore-exceptions` was being set elsewhere, so now programs
fail to build when using `cxx` if any `throw` or `try ... catch` are used.

> error: cannot use 'try' with exceptions disabled

Instead for trycatch just call `func()`.